# Index Table Preparation

In [6]:
import geopandas as gpd
import pandas as pd
from pathlib import Path

# config
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

Pandas notes for me: 

gdf.loc[ROWS, COLUMNS] = "select rows by this value, and columns by this value"

new field:
gdf["new_field"] = (
    gdf["field_a"].astype(str)
    + "_"
    + gdf["field_b"].astype(str)
    + "_"
    + gdf["field_c"].astype(str)
)

### Load the Shapefile and give it a true unique ID before doing anything else to it.

In [7]:
# this is the path to the original feature service, downloaded as a shapefile from here: 
# https://www.arcgis.com/home/item.html?id=f260e4065a384e7ebee05b23362f380f#overview
# Layer 36112 - https://gis5.uspatial.umn.edu/arcgis/rest/services/mhapo/MHAPO_dynamic/MapServer/0
original_index_path = "data/historic_airphoto_index/shapefiles/umn_airphoto_index_original.shp"

gdf_original = gpd.read_file(original_index_path)

print(gdf_original.crs)
# we're keeping this in web mercator for now.

EPSG:3857

In [8]:
# make a unique identifier

gdf_original["source_id"] = range(1, len(gdf_original) + 1)

assert gdf_original["source_id"].is_unique
assert gdf_original["source_id"].notna().all()

In [9]:
gdf_original

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id
0,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07185.jpg\t,bxq07185,46.964901,-94.303902,1939.0,1,1,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10497862.317 5936346.903),1
1,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07187.jpg\t,bxq07187,46.965599,-94.346802,1939.0,2,2,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10502637.934 5936460.776),2
2,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07189.jpg\t,bxq07189,46.966202,-94.389801,1939.0,3,3,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10507424.583 5936559.09),3
3,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07191.jpg\t,bxq07191,46.966801,-94.432800,1939.0,4,4,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10512211.244 5936656.784),4
4,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07195.jpg\t,bxq07195,46.967999,-94.518700,1939.0,5,5,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10521773.51 5936852.176),5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115744,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-041.jpg,WB-4A-041,43.948613,-92.515435,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10298771.078 5457493.316),115745
115745,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-043.jpg,WB-4A-043,43.948634,-92.558712,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10303588.744 5457496.692),115746
115746,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-045.jpg,WB-4A-045,43.948656,-92.601990,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10308406.41 5457500.067),115747
115747,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-047.jpg,WB-4A-047,43.948678,-92.645268,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10313224.077 5457503.444),115748
115748,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-049.jpg,WB-4A-049,43.948700,-92.688546,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10318041.743 5457506.819),115749

In [10]:
gdf_original.to_file(
    "data/historic_airphoto_index/umn_index_original_with_source_id.gpkg",
    driver="GPKG"
)

### Cleaning the original table

In [11]:
gdf_clean = gdf_original.copy()

#preview the columns
gdf_clean.columns

Index(['flight_cod', 'url_link', 'photo_id', 'lat', 'long_', 'year_',
       'objectid_1', 'in_fid', 'near_fid', 'near_dist', 'objectid_2',
       'statefp10', 'countyfp10', 'countyns10', 'geoid10', 'name10',
       'namelsad10', 'lsad10', 'classfp10', 'mtfcc10', 'csafp10', 'cbsafp10',
       'metdivfp10', 'funcstat10', 'aland10', 'awater10', 'intptlat10',
       'intptlon10', 'year_conve', 'decade', 'decade_dat', 'decade_str',
       'created_us', 'created_da', 'last_edite', 'last_edi_1', 'geometry',
       'source_id'],
      dtype='str')

#### Cleaning the URLs
And looking for true duplicates...

In [12]:
# clean URL spaces

gdf_clean["url_link"] = gdf_clean["url_link"].str.strip()

In [13]:
exists = 'https://geo.lib.umn.edu/Olmsted/1940/WB-3A-115.jpg' in gdf_clean['url_link'].values

exists

False

In [14]:
# identify duplicate URLs

duplicates = gdf_clean[gdf_clean["url_link"].duplicated(keep=False)]
duplicates = duplicates.sort_values(by=['flight_cod','url_link'])
duplicates

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id
110838,Hennepin,https://geo.lib.umn.edu/Hennepin_County/y1937/WN-10-867.jpg,WN-10-867,45.163490,-93.371491,1937.0,112117,112117,47,0.0,47,27,053,00659472,27053,Hennepin,Hennepin County,06,H1,G4020,378,33460,None,A,1.433794e+09,137155436.0,+45.0060644,-093.4751846,1937-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10394066.859 5647296.475),110839
110840,Hennepin,https://geo.lib.umn.edu/Hennepin_County/y1937/WN-10-867.jpg,WN-10-867,45.185798,-93.371902,1937.0,112119,112119,76,0.0,76,27,003,00659447,27003,Anoka,Anoka County,06,H1,G4020,378,33460,None,A,1.095590e+09,59831077.0,+45.2741098,-093.2427232,1937-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10394112.585 5650819.159),110841
115716,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-101,43.860098,-92.079152,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10250204.313 5443817.49),115717
115717,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-103,43.860376,-92.121252,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10254890.84 5443860.455),115718
115718,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-105,43.860655,-92.163352,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10259577.367 5443903.419),115719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48032,koo,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/koo/y1988/koo_35_052.jpg,koo_35_052,47.926300,-93.339203,1988.0,49248,49220,53,0.0,53,27,071,00659481,27071,Koochiching,Koochiching County,06,H1,G4020,NaN,NaN,None,A,8.039504e+09,129375868.0,+48.2454895,-093.7828417,1988-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10390472.538 6094602.527),48033
19098,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_1dd_235.jpg,wp_1dd_235,45.196300,-93.662903,1963.0,20314,20286,68,0.0,68,27,171,00659530,27171,Wright,Wright County,06,H1,G4020,378,33460,None,A,1.713165e+09,136781631.0,+45.1750914,-093.9663965,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10426506.646 5652478.103),19099
19099,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_1dd_235.jpg,wp_1dd_235,45.195499,-93.642502,1963.0,20315,20287,47,0.0,47,27,053,00659472,27053,Hennepin,Hennepin County,06,H1,G4020,378,33460,None,A,1.433794e+09,137155436.0,+45.0060644,-093.4751846,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10424235.617 5652351.553),19100
14664,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_2dd_209.jpg,wp_2dd_209,44.994202,-94.099800,1963.0,15418,14790,68,0.0,68,27,171,00659530,27171,Wright,Wright County,06,H1,G4020,378,33460,None,A,1.713165e+09,136781631.0,+45.1750914,-093.9663965,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10475141.831 5620608.709),14665
14672,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_2dd_209.jpg,wp_2dd_209,44.995098,-94.256203,1963.0,15426,14798,36,0.0,36,27,093,00659492,27093,Meeker,Meeker County,06,H1,G4020,NaN,NaN,None,A,1.575175e+09,94784627.0,+45.1231555,-094.5273460,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10492552.489 5620749.815),14673

In [15]:
# identify duplicate URLs with unique photo_ids to be fixed

fake_duplicates = gdf_clean[
    gdf_clean["url_link"].duplicated(keep=False)
    & ~gdf_clean["photo_id"].duplicated(keep=False)]
fake_duplicates = fake_duplicates.sort_values(by=['flight_cod','url_link'])
fake_duplicates

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id
115716,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-101,43.860098,-92.079152,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10250204.313 5443817.49),115717
115717,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-103,43.860376,-92.121252,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10254890.84 5443860.455),115718
115718,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-105,43.860655,-92.163352,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10259577.367 5443903.419),115719
115719,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-107,43.860933,-92.205451,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10264263.894 5443946.384),115720
115720,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-109,43.861211,-92.247551,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10268950.42 5443989.348),115721
115721,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-111,43.861489,-92.289651,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10273636.947 5444032.314),115722
115722,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-113,43.861768,-92.331751,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10278323.473 5444075.278),115723
115723,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-115,43.862046,-92.373851,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10283010 5444118.244),115724
115724,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-117,43.862324,-92.415950,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10287696.528 5444161.211),115725
115725,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-119,43.862603,-92.458050,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10292383.054 5444204.176),115726
115726,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-121,43.862881,-92.500150,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10297069.581 5444247.143),115727
115727,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-123,43.863159,-92.542250,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10301756.107 5444290.108),115728
115728,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-125,43.863437,-92.584349,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10306442.634 5444333.075),115729
115729,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-127,43.863716,-92.626449,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10311129.16 5444376.041),115730
115730,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg,WB-3A-129,43.863994,-92.668549,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10315815.687 5444419.008),115731

In [16]:
# fix olmsted county URLs

bad_url = "https://geo.lib.umn.edu/Olmsted/1940/WB-3A-101.jpg"

mask = gdf_clean["url_link"] == bad_url

gdf_clean.loc[mask, "url_link"] = (
    "https://geo.lib.umn.edu/Olmsted/1940/"
    + gdf_clean.loc[mask, "photo_id"]
    + ".jpg"
)

In [17]:
check = gdf_clean[gdf_clean["flight_cod"] == "Olmsted"]

check

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id
115588,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-1A-003.jpg,WB-1A-003,44.181032,-92.303203,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10275145.556 5493500.176),115589
115589,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-1A-005.jpg,WB-1A-005,44.181175,-92.347837,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10280114.246 5493522.412),115590
115590,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-1A-007.jpg,WB-1A-007,44.181319,-92.392472,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10285082.936 5493544.649),115591
115591,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-1A-009.jpg,WB-1A-009,44.181462,-92.437106,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10290051.626 5493566.885),115592
115592,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-1A-011.jpg,WB-1A-011,44.181605,-92.481741,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10295020.316 5493589.121),115593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115744,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-041.jpg,WB-4A-041,43.948613,-92.515435,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10298771.078 5457493.316),115745
115745,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-043.jpg,WB-4A-043,43.948634,-92.558712,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10303588.744 5457496.692),115746
115746,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-045.jpg,WB-4A-045,43.948656,-92.601990,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10308406.41 5457500.067),115747
115747,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-047.jpg,WB-4A-047,43.948678,-92.645268,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10313224.077 5457503.444),115748
115748,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-049.jpg,WB-4A-049,43.948700,-92.688546,1940.0,0,0,0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.0,0.0,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10318041.743 5457506.819),115749

In [18]:
# identify duplicate URLs again

duplicates = gdf_clean[gdf_clean["url_link"].duplicated(keep=False)]
duplicates = duplicates.sort_values(by=['flight_cod','url_link'])
duplicates

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id
110838,Hennepin,https://geo.lib.umn.edu/Hennepin_County/y1937/WN-10-867.jpg,WN-10-867,45.163490,-93.371491,1937.0,112117,112117,47,0.0,47,27,053,00659472,27053,Hennepin,Hennepin County,06,H1,G4020,378,33460,None,A,1.433794e+09,137155436.0,+45.0060644,-093.4751846,1937-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10394066.859 5647296.475),110839
110840,Hennepin,https://geo.lib.umn.edu/Hennepin_County/y1937/WN-10-867.jpg,WN-10-867,45.185798,-93.371902,1937.0,112119,112119,76,0.0,76,27,003,00659447,27003,Anoka,Anoka County,06,H1,G4020,378,33460,None,A,1.095590e+09,59831077.0,+45.2741098,-093.2427232,1937-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10394112.585 5650819.159),110841
55760,ait,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/ait/y1975/ait_6_144.jpg,ait_6_144,47.007702,-93.069901,1975.0,56976,56961,66,0.0,66,27,001,00663198,27001,Aitkin,Aitkin County,06,H1,G4020,NaN,NaN,None,A,4.718084e+09,449700337.0,+46.6024464,-093.4197600,1975-01-01,1970,NaT,1970,None,NaT,BORCHERT,2026-07-31,POINT (-10360493.932 5943331.309),55761
57982,ait,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/ait/y1975/ait_6_144.jpg,ait_6_144,46.524502,-93.137703,1975.0,59198,59198,66,0.0,66,27,001,00663198,27001,Aitkin,Aitkin County,06,H1,G4020,NaN,NaN,None,A,4.718084e+09,449700337.0,+46.6024464,-093.4197600,1975-01-01,1970,NaT,1970,None,NaT,BORCHERT,2026-07-31,POINT (-10368041.66 5864803.111),57983
56600,ait,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/ait/y1982/ait_1_100.jpg,ait_1_100,46.952801,-93.761101,1982.0,57816,57816,66,0.0,66,27,001,00663198,27001,Aitkin,Aitkin County,06,H1,G4020,NaN,NaN,None,A,4.718084e+09,449700337.0,+46.6024464,-093.4197600,1982-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10437437.997 5934373.362),56601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48032,koo,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/koo/y1988/koo_35_052.jpg,koo_35_052,47.926300,-93.339203,1988.0,49248,49220,53,0.0,53,27,071,00659481,27071,Koochiching,Koochiching County,06,H1,G4020,NaN,NaN,None,A,8.039504e+09,129375868.0,+48.2454895,-093.7828417,1988-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10390472.538 6094602.527),48033
19098,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_1dd_235.jpg,wp_1dd_235,45.196300,-93.662903,1963.0,20314,20286,68,0.0,68,27,171,00659530,27171,Wright,Wright County,06,H1,G4020,378,33460,None,A,1.713165e+09,136781631.0,+45.1750914,-093.9663965,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10426506.646 5652478.103),19099
19099,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_1dd_235.jpg,wp_1dd_235,45.195499,-93.642502,1963.0,20315,20287,47,0.0,47,27,053,00659472,27053,Hennepin,Hennepin County,06,H1,G4020,378,33460,None,A,1.433794e+09,137155436.0,+45.0060644,-093.4751846,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10424235.617 5652351.553),19100
14664,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_2dd_209.jpg,wp_2dd_209,44.994202,-94.099800,1963.0,15418,14790,68,0.0,68,27,171,00659530,27171,Wright,Wright County,06,H1,G4020,378,33460,None,A,1.713165e+09,136781631.0,+45.1750914,-093.9663965,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10475141.831 5620608.709),14665
14672,wp,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/wp/y1963/wp_2dd_209.jpg,wp_2dd_209,44.995098,-94.256203,1963.0,15426,14798,36,0.0,36,27,093,00659492,27093,Meeker,Meeker County,06,H1,G4020,NaN,NaN,None,A,1.575175e+09,94784627.0,+45.1231555,-094.5273460,1963-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10492552.489 5620749.815),14673

In [19]:
# drop duplicates arbitrarily (the only thing that varies is the geometry and we're not using it.)
gdf_clean = gdf_clean.drop_duplicates(
    subset=["url_link"],
    keep="first"
).copy()

In [20]:
# identify duplicate URLs again
# there should be none. 

duplicates = gdf_clean[gdf_clean["photo_id"].duplicated(keep=False)]
duplicates = duplicates.sort_values(by=['flight_cod','photo_id'])
duplicates

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id
99281,Hennepin,https://geo.lib.umn.edu/Dakota_County/y1940/WK-4A-145.jpg,WN-4A-145,45.048962,-93.418001,1940.0,100560,100560,47,0.000000,47,27,053,00659472,27053,Hennepin,Hennepin County,06,H1,G4020,378,33460,None,A,1.433794e+09,1.371554e+08,+45.0060644,-093.4751846,1940-01-01,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10399244.302 5629232.847),99282
112241,Hennepin,https://geo.lib.umn.edu/Hennepin_County/y1940/WN-4A-145.jpg,WN-4A-145,45.049315,-93.418311,1940.0,0,0,0,0.000000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10399278.789 5629288.499),112242
97701,Washington,https://geo.lib.umn.edu/washington/y1936/ccz-1-10.jpg,ccz-1-10,45.222364,-93.001213,1936.0,98980,98980,34,0.000000,34,27,163,00659526,27163,Washington,Washington County,06,H1,G4020,378,33460,None,A,9.952855e+08,9.961890e+07,+45.0379290,-092.8901170,1936-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10352847.674 5656596.342),97702
97891,Washington,https://geo.lib.umn.edu/washington/y1938/ccz-1-10.jpg,ccz-1-10,44.898016,-92.761724,1938.0,99170,99170,34,1169.694738,34,27,163,00659526,27163,Washington,Washington County,06,H1,G4020,378,33460,None,A,9.952855e+08,9.961890e+07,+45.0379290,-092.8901170,1938-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10326187.881 5605480.456),97892
97703,Washington,https://geo.lib.umn.edu/washington/y1936/ccz-1-12.jpg,ccz-1-12,45.249043,-93.000414,1936.0,98982,98982,34,0.000000,34,27,163,00659526,27163,Washington,Washington County,06,H1,G4020,378,33460,None,A,9.952855e+08,9.961890e+07,+45.0379290,-092.8901170,1936-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10352758.73 5660813.79),97704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66235,stl,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/stl/y1981/stl_028_105.jpg,stl_028_105,47.663601,-92.936997,1981.0,67451,67213,32,0.000000,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1981-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10345699.126 6051071.368),66236
61878,stl,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/stl/y1989/stl_028_106.jpg,stl_028_106,46.838799,-92.226402,1989.0,63094,63094,32,0.000000,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1989-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10266596.142 5915801.464),61879
66236,stl,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/stl/y1981/stl_028_106.jpg,stl_028_106,47.662399,-92.955299,1981.0,67452,67214,32,0.000000,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1981-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10347736.596 6050872.758),66237
61879,stl,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/stl/y1989/stl_028_107.jpg,stl_028_107,46.824902,-92.225800,1989.0,63095,63095,32,0.000000,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1989-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10266529.05 5913540.242),61880
66237,stl,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/projects/stl/y1981/stl_028_107.jpg,stl_028_107,47.662701,-92.975197,1981.0,67453,67215,32,0.000000,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1981-01-01,1980,NaT,1980,None,NaT,BORCHERT,2026-07-31,POINT (-10349951.564 6050922.575),66238

In [21]:
print("Unique URLs:", gdf_clean["url_link"].is_unique)
print("Remaining records:", len(gdf_clean))

Unique URLs: True
Remaining records: 115577

### Clean up other values

In [22]:
# convert year field to an integer rather than a float
# handles missing values
gdf_clean["year_"] = gdf_clean["year_"].astype("Int64")

In [23]:
# populate missing counties from the flight code field
gdf_clean["name10"] = gdf_clean["name10"].fillna(
    gdf_clean["flight_cod"]
)

In [24]:
# check for nulls
print(gdf_clean["name10"].isna().any())

print(gdf_clean["year_"].isna().any())

print(gdf_clean["photo_id"].isna().any())

print(gdf_clean["url_link"].isna().any())

False
False
False
False

### Adding filename identifier and validation

In [25]:
# add a new unique, human readable identifier field called "cty_year_id"
# it will be used for naming files
# it is a combination of the county, the year, and the photo ID. 

gdf_clean["cty_year_id"] = (
    gdf_clean["name10"].str.strip().str.lower().str.replace(" ", "_").str.replace('.', '', regex=False)
    + "_"
    + gdf_clean["year_"].astype("string")
    + "_"
    + gdf_clean["photo_id"].str.strip().str.lower().str.replace(" ", "_")
)

# add a number to any non-unique values produced by this
counts = gdf_clean.groupby("cty_year_id").cumcount()

gdf_clean["cty_year_id"] += counts.map(
    lambda n: f"_{n}" if n > 0 else ""
)

In [26]:
# validate that the periods were handled correctly
gdf_clean_filtered = gdf_clean.loc[gdf_clean["name10"] == "St. Louis"]

gdf_clean_filtered

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id,cty_year_id
41857,cir,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/cir/y1961/cir_002_121.jpg,cir_002_121,48.379299,-93.070099,1961,43073,43045,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1961-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10360516.018 6170190.286),41858,st_louis_1961_cir_002_121
41858,cir,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/cir/y1961/cir_002_122.jpg,cir_002_122,48.392399,-93.070396,1961,43074,43046,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1961-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10360549.135 6172386.065),41859,st_louis_1961_cir_002_122
41859,cir,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/cir/y1961/cir_002_123.jpg,cir_002_123,48.405800,-93.068802,1961,43075,43047,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1961-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10360371.636 6174632.968),41860,st_louis_1961_cir_002_123
41860,cir,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/cir/y1961/cir_003_120.jpg,cir_003_120,48.375900,-93.033997,1961,43076,43048,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1961-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10356497.128 6169620.649),41861,st_louis_1961_cir_003_120
41861,cir,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/cir/y1961/cir_003_121.jpg,cir_003_121,48.389000,-93.032997,1961,43077,43049,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1961-01-01,1960,NaT,1960,None,NaT,BORCHERT,2026-07-31,POINT (-10356385.864 6171816.281),41862,st_louis_1961_cir_003_121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108032,Lake,https://geo.lib.umn.edu/Lake/1939/CIS-6-029.jpg,CIS-6-029,46.968823,-91.808008,1939,109311,109311,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10220020.667 5936986.689),108033,st_louis_1939_cis-6-029
108033,Lake,https://geo.lib.umn.edu/Lake/1939/CIS-6-030.jpg,CIS-6-030,46.956342,-91.807631,1939,109312,109312,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10219978.708 5934950.935),108034,st_louis_1939_cis-6-030
108034,Lake,https://geo.lib.umn.edu/Lake/1939/CIS-6-031.jpg,CIS-6-031,46.943862,-91.807254,1939,109313,109313,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10219936.749 5932915.656),108035,st_louis_1939_cis-6-031
108035,Lake,https://geo.lib.umn.edu/Lake/1939/CIS-6-032.jpg,CIS-6-032,46.931381,-91.806877,1939,109314,109314,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10219894.79 5930880.851),108036,st_louis_1939_cis-6-032
108036,Lake,https://geo.lib.umn.edu/Lake/1939/CIS-6-033.jpg,CIS-6-033,46.918900,-91.806500,1939,109315,109315,32,0.0,32,27,137,00662850,27137,St. Louis,St. Louis County,06,H1,G4020,NaN,20260,None,A,1.618069e+10,1.585336e+09,+47.5838524,-092.4636448,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2025-12-15,POINT (-10219852.832 5928846.52),108037,st_louis_1939_cis-6-033

In [27]:
# validate that this new field is unique and contains no nulls
# should return 

print(f"All unique values:", gdf_clean['cty_year_id'].is_unique)
print(f"Has null values:", gdf_clean['cty_year_id'].isna().any())
print(f"Has spaces:", gdf_clean['cty_year_id'].str.contains(' ').any())

All unique values: True
Has null values: False
Has spaces: False

In [28]:
# check it out
gdf_clean

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,geometry,source_id,cty_year_id
0,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07185.jpg,bxq07185,46.964901,-94.303902,1939,1,1,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10497862.317 5936346.903),1,cass_1939_bxq07185
1,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07187.jpg,bxq07187,46.965599,-94.346802,1939,2,2,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10502637.934 5936460.776),2,cass_1939_bxq07187
2,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07189.jpg,bxq07189,46.966202,-94.389801,1939,3,3,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10507424.583 5936559.09),3,cass_1939_bxq07189
3,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07191.jpg,bxq07191,46.966801,-94.432800,1939,4,4,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10512211.244 5936656.784),4,cass_1939_bxq07191
4,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07195.jpg,bxq07195,46.967999,-94.518700,1939,5,5,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,POINT (-10521773.51 5936852.176),5,cass_1939_bxq07195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115744,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-041.jpg,WB-4A-041,43.948613,-92.515435,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10298771.078 5457493.316),115745,olmsted_1940_wb-4a-041
115745,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-043.jpg,WB-4A-043,43.948634,-92.558712,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10303588.744 5457496.692),115746,olmsted_1940_wb-4a-043
115746,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-045.jpg,WB-4A-045,43.948656,-92.601990,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10308406.41 5457500.067),115747,olmsted_1940_wb-4a-045
115747,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-047.jpg,WB-4A-047,43.948678,-92.645268,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10313224.077 5457503.444),115748,olmsted_1940_wb-4a-047
115748,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-049.jpg,WB-4A-049,43.948700,-92.688546,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,POINT (-10318041.743 5457506.819),115749,olmsted_1940_wb-4a-049

In [29]:
# save it
gdf_clean.to_file("data/historic_airphoto_index/umn_index_cleaned_ogcolumns.gpkg")

### Drop and reorder columns

In [30]:
# open cleaned table
path = "data/historic_airphoto_index/umn_index_cleaned_ogcolumns.gpkg"

gdf = gpd.read_file(path)

In [31]:
gdf

,flight_cod,url_link,photo_id,lat,long_,year_,objectid_1,in_fid,near_fid,near_dist,objectid_2,statefp10,countyfp10,countyns10,geoid10,name10,namelsad10,lsad10,classfp10,mtfcc10,csafp10,cbsafp10,metdivfp10,funcstat10,aland10,awater10,intptlat10,intptlon10,year_conve,decade,decade_dat,decade_str,created_us,created_da,last_edite,last_edi_1,source_id,cty_year_id,geometry
0,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07185.jpg,bxq07185,46.964901,-94.303902,1939,1,1,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,1,cass_1939_bxq07185,POINT (-10497862.317 5936346.903)
1,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07187.jpg,bxq07187,46.965599,-94.346802,1939,2,2,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,2,cass_1939_bxq07187,POINT (-10502637.934 5936460.776)
2,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07189.jpg,bxq07189,46.966202,-94.389801,1939,3,3,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,3,cass_1939_bxq07189,POINT (-10507424.583 5936559.09)
3,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07191.jpg,bxq07191,46.966801,-94.432800,1939,4,4,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,4,cass_1939_bxq07191,POINT (-10512211.244 5936656.784)
4,bxq,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07195.jpg,bxq07195,46.967999,-94.518700,1939,5,5,85,0.0,85,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,NaN,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,1939-01-01,1930,NaT,1930,None,NaT,BORCHERT,2026-07-31,5,cass_1939_bxq07195,POINT (-10521773.51 5936852.176)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115572,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-041.jpg,WB-4A-041,43.948613,-92.515435,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,115745,olmsted_1940_wb-4a-041,POINT (-10298771.078 5457493.316)
115573,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-043.jpg,WB-4A-043,43.948634,-92.558712,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,115746,olmsted_1940_wb-4a-043,POINT (-10303588.744 5457496.692)
115574,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-045.jpg,WB-4A-045,43.948656,-92.601990,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,115747,olmsted_1940_wb-4a-045,POINT (-10308406.41 5457500.067)
115575,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-047.jpg,WB-4A-047,43.948678,-92.645268,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,115748,olmsted_1940_wb-4a-047,POINT (-10313224.077 5457503.444)
115576,Olmsted,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-049.jpg,WB-4A-049,43.948700,-92.688546,1940,0,0,0,0.0,0,NaN,NaN,NaN,NaN,Olmsted,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaT,1940,NaT,1940,None,NaT,BORCHERT,2025-12-15,115749,olmsted_1940_wb-4a-049,POINT (-10318041.743 5457506.819)

In [32]:
# inspect
gdf.columns

Index(['flight_cod', 'url_link', 'photo_id', 'lat', 'long_', 'year_',
       'objectid_1', 'in_fid', 'near_fid', 'near_dist', 'objectid_2',
       'statefp10', 'countyfp10', 'countyns10', 'geoid10', 'name10',
       'namelsad10', 'lsad10', 'classfp10', 'mtfcc10', 'csafp10', 'cbsafp10',
       'metdivfp10', 'funcstat10', 'aland10', 'awater10', 'intptlat10',
       'intptlon10', 'year_conve', 'decade', 'decade_dat', 'decade_str',
       'created_us', 'created_da', 'last_edite', 'last_edi_1', 'source_id',
       'cty_year_id', 'geometry'],
      dtype='str')

In [33]:
# rename
new_gdf = gdf.rename(columns={
    "url_link" : "url",
    "year_" : "year",
    "name10" : "county",
    'flight_cod' : 'flight_code'
})

In [36]:
# add
new_gdf["worldfile_json"] = None
new_gdf["h_extent"] = None
new_gdf["scale"] = None
new_gdf["dpi_x"] = None
new_gdf["width_px"] = None
new_gdf["status"] = None
new_gdf["gcp_count"] = None
new_gdf["confidence"] = None
new_gdf["date_download"] = None
new_gdf["date_georef"] = None

In [37]:
# reorder and drop
new_gdf = new_gdf[['cty_year_id','status','county','year','photo_id','h_extent','gcp_count','confidence','scale','dpi_x','width_px','worldfile_json','url','flight_code','source_id','geometry','date_download','date_georef']]

new_gdf

,cty_year_id,status,county,year,photo_id,h_extent,gcp_count,confidence,scale,dpi_x,width_px,worldfile_json,url,flight_code,source_id,geometry,date_download,date_georef
0,cass_1939_bxq07185,None,Cass,1939,bxq07185,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07185.jpg,bxq,1,POINT (-10497862.317 5936346.903),None,None
1,cass_1939_bxq07187,None,Cass,1939,bxq07187,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07187.jpg,bxq,2,POINT (-10502637.934 5936460.776),None,None
2,cass_1939_bxq07189,None,Cass,1939,bxq07189,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07189.jpg,bxq,3,POINT (-10507424.583 5936559.09),None,None
3,cass_1939_bxq07191,None,Cass,1939,bxq07191,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07191.jpg,bxq,4,POINT (-10512211.244 5936656.784),None,None
4,cass_1939_bxq07195,None,Cass,1939,bxq07195,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxq/y1939/bxq07195.jpg,bxq,5,POINT (-10521773.51 5936852.176),None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115572,olmsted_1940_wb-4a-041,None,Olmsted,1940,WB-4A-041,None,None,None,None,None,None,None,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-041.jpg,Olmsted,115745,POINT (-10298771.078 5457493.316),None,None
115573,olmsted_1940_wb-4a-043,None,Olmsted,1940,WB-4A-043,None,None,None,None,None,None,None,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-043.jpg,Olmsted,115746,POINT (-10303588.744 5457496.692),None,None
115574,olmsted_1940_wb-4a-045,None,Olmsted,1940,WB-4A-045,None,None,None,None,None,None,None,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-045.jpg,Olmsted,115747,POINT (-10308406.41 5457500.067),None,None
115575,olmsted_1940_wb-4a-047,None,Olmsted,1940,WB-4A-047,None,None,None,None,None,None,None,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-047.jpg,Olmsted,115748,POINT (-10313224.077 5457503.444),None,None
115576,olmsted_1940_wb-4a-049,None,Olmsted,1940,WB-4A-049,None,None,None,None,None,None,None,https://geo.lib.umn.edu/Olmsted/1940/WB-4A-049.jpg,Olmsted,115749,POINT (-10318041.743 5457506.819),None,None

In [38]:
new_gdf = new_gdf.sort_values(by=['county','year'], ascending=[True, True])

new_gdf

,cty_year_id,status,county,year,photo_id,h_extent,gcp_count,confidence,scale,dpi_x,width_px,worldfile_json,url,flight_code,source_id,geometry,date_download,date_georef
17231,aitkin_1939_bxv02017,None,Aitkin,1939,bxv02017,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxv/y1939/bxv02017.jpg,bxv,17233,POINT (-10383436.935 5806733.399),None,None
17324,aitkin_1939_bxt03191,None,Aitkin,1939,bxt03191,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxt/y1939/bxt03191.jpg,bxt,17326,POINT (-10442747.814 5821533.312),None,None
17325,aitkin_1939_bxt03192,None,Aitkin,1939,bxt03192,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxt/y1939/bxt03192.jpg,bxt,17327,POINT (-10440599.092 5821517.341),None,None
17346,aitkin_1939_byd03058,None,Aitkin,1939,byd03058,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/byd/y1939/byd03058.jpg,byd,17348,POINT (-10359703.23 5813165.04),None,None
17348,aitkin_1939_byd04003,None,Aitkin,1939,byd04003,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/byd/y1939/byd04003.jpg,byd,17350,POINT (-10358746.071 5818024.084),None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9646,yellow_medicine_1991_napp_4112_148,None,Yellow Medicine,1991,napp_4112_148,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4112_148.jpg,napp,9647,POINT (-10655011.753 5597325.517),None,None
9647,yellow_medicine_1991_napp_4112_149,None,Yellow Medicine,1991,napp_4112_149,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4112_149.jpg,napp,9648,POINT (-10655123.006 5602256.72),None,None
9648,yellow_medicine_1991_napp_4113_036,None,Yellow Medicine,1991,napp_4113_036,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4113_036.jpg,napp,9649,POINT (-10648610.57 5601707.206),None,None
9649,yellow_medicine_1991_napp_4113_037,None,Yellow Medicine,1991,napp_4113_037,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4113_037.jpg,napp,9650,POINT (-10648410.986 5596854.756),None,None
9651,yellow_medicine_1991_napp_4117_059,None,Yellow Medicine,1991,napp_4117_059,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4117_059.jpg,napp,9652,POINT (-10669183.169 5601958.294),None,None

### Export

In [39]:
new_gdf.to_file("data/historic_airphoto_index/main_index_blank.gpkg")

### Edit Fields Later

In [2]:
edited_gdf = gpd.read_file("data/historic_airphoto_index/main_index_blank.gpkg")

In [ ]:
# add columns
edited_gdf["date_download"] = None
edited_gdf["date_georef"] = None

In [4]:
edited_gdf.to_file("data/historic_airphoto_index/main_index_blank.gpkg")

In [5]:
edited_gdf

,cty_year_id,status,county,year,photo_id,h_extent,gcp_count,confidence,scale,dpi_x,width_px,worldfile_json,url,flight_code,source_id,geometry,date_download,date_georef
0,aitkin_1939_bxv02017,None,Aitkin,1939,bxv02017,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxv/y1939/bxv02017.jpg,bxv,17233,POINT (-10383436.935 5806733.399),None,None
1,aitkin_1939_bxt03191,None,Aitkin,1939,bxt03191,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxt/y1939/bxt03191.jpg,bxt,17326,POINT (-10442747.814 5821533.312),None,None
2,aitkin_1939_bxt03192,None,Aitkin,1939,bxt03192,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/bxt/y1939/bxt03192.jpg,bxt,17327,POINT (-10440599.092 5821517.341),None,None
3,aitkin_1939_byd03058,None,Aitkin,1939,byd03058,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/byd/y1939/byd03058.jpg,byd,17348,POINT (-10359703.23 5813165.04),None,None
4,aitkin_1939_byd04003,None,Aitkin,1939,byd04003,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usda/byd/y1939/byd04003.jpg,byd,17350,POINT (-10358746.071 5818024.084),None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115572,yellow_medicine_1991_napp_4112_148,None,Yellow Medicine,1991,napp_4112_148,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4112_148.jpg,napp,9647,POINT (-10655011.753 5597325.517),None,None
115573,yellow_medicine_1991_napp_4112_149,None,Yellow Medicine,1991,napp_4112_149,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4112_149.jpg,napp,9648,POINT (-10655123.006 5602256.72),None,None
115574,yellow_medicine_1991_napp_4113_036,None,Yellow Medicine,1991,napp_4113_036,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4113_036.jpg,napp,9649,POINT (-10648610.57 5601707.206),None,None
115575,yellow_medicine_1991_napp_4113_037,None,Yellow Medicine,1991,napp_4113_037,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4113_037.jpg,napp,9650,POINT (-10648410.986 5596854.756),None,None
115576,yellow_medicine_1991_napp_4117_059,None,Yellow Medicine,1991,napp_4117_059,None,None,None,None,None,None,None,https://geo.lib.umn.edu/dnr_historical_aerial_imagery/airphotos/usgs/napp/y1991/napp_4117_059.jpg,napp,9652,POINT (-10669183.169 5601958.294),None,None